package ontology

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

// codeVocabulary declares the am: classes and predicates the code graph uses, so code.ttl is a
// self-describing ontology rather than an ad-hoc set of triples (the structural project.ttl reuses
// the same namespace). Kept intentionally small and focused.
const codeVocabulary = `# --- Andromeda code-graph vocabulary (am:) ---
am:Package a rdfs:Class ; rdfs:label "Package" ; rdfs:comment "A Go package (one source directory)." .
am:Type a rdfs:Class ; rdfs:label "Type" ; rdfs:comment "A named type declaration." .
am:Struct a rdfs:Class ; rdfs:subClassOf am:Type ; rdfs:label "Struct" .
am:Interface a rdfs:Class ; rdfs:subClassOf am:Type ; rdfs:label "Interface" .
am:Function a rdfs:Class ; rdfs:label "Function" ; rdfs:comment "A package-level function." .
am:Method a rdfs:Class ; rdfs:subClassOf am:Function ; rdfs:label "Method" ; rdfs:comment "A function with a receiver." .
am:inPackage a rdf:Property ; rdfs:comment "Declaring package of a type or function." .
am:declares a rdf:Property ; rdfs:domain am:Package ; rdfs:comment "A type or function a package declares." .
am:imports a rdf:Property ; rdfs:domain am:Package ; rdfs:range am:Package ; rdfs:comment "A module-internal package this package imports." .
am:definedIn a rdf:Property ; rdfs:range am:File ; rdfs:comment "The file a declaration lives in." .
am:hasMethod a rdf:Property ; rdfs:domain am:Type ; rdfs:range am:Method ; rdfs:comment "A method whose receiver is this type." .
am:receiver a rdf:Property ; rdfs:domain am:Method ; rdfs:comment "Receiver type name of a method." .
am:calls a rdf:Property ; rdfs:domain am:Function ; rdfs:range am:Function ; rdfs:comment "Resolved same-package function call." .
am:callsApprox a rdf:Property ; rdfs:domain am:Function ; rdfs:range am:Function ; rdfs:comment "Cross-package call resolved from a package selector (no full type checking)." .
am:implements a rdf:Property ; rdfs:domain am:Type ; rdfs:range am:Interface ; rdfs:comment "Structural interface satisfaction (method-name containment; a heuristic, not type-checked)." .
am:exported a rdf:Property ; rdfs:comment "Whether an identifier is exported." .
am:packageName a rdf:Property .
am:importPath a rdf:Property .
am:paramCount a rdf:Property .
am:resultCount a rdf:Property .
am:externalImportCount a rdf:Property ; rdfs:comment "Number of non-module (stdlib/third-party) imports; those edges are omitted to keep the graph focused on internal correlations." .

`

// WriteCode streams the code graph to <root>/.andromeda/ontology/code.ttl, one package at a time via
// a buffered writer, so memory and output stay bounded regardless of repo size (the "por lotes"
// requirement). Written atomically (temp file + rename). Returns the code.ttl path and a sha256 over
// its exact bytes (a deterministic content hash for the manifest).
func WriteCode(root string, cm *CodeModel) (string, string, error) {
	dir := filepath.Join(root, markerDir, ontologySubdir)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", "", err
	}
	path := filepath.Join(dir, "code.ttl")
	tmp := path + ".tmp"
	f, err := os.OpenFile(tmp, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600) //nolint:gosec // fixed path under the workspace marker dir
	if err != nil {
		return "", "", err
	}
	h := sha256.New()
	w := bufio.NewWriter(io.MultiWriter(f, h))
	writeCodeTTL(w, cm)
	if flushErr := w.Flush(); flushErr != nil {
		_ = f.Close()
		_ = os.Remove(tmp)
		return "", "", flushErr
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(tmp)
		return "", "", err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return "", "", err
	}
	return path, hex.EncodeToString(h.Sum(nil)), nil
}

// writeCodeTTL serializes the code model as Turtle: prologue + vocabulary, then a streamed block per
// package (nodes for the package, its types, and its functions), then the cross-package call and
// implements edges. Deterministic — no timestamps — given a deterministic CodeModel.
func writeCodeTTL(w io.Writer, cm *CodeModel) {
	io.WriteString(w, "# Andromeda code graph — an AST-level map of this workspace's Go packages.\n")
	io.WriteString(w, "# Generated by `andromeda ontology`; regenerate to update, do not hand-edit.\n")
	if cm.ModulePath != "" {
		io.WriteString(w, "# module: "+cm.ModulePath+"\n")
	}
	if cm.Truncated {
		io.WriteString(w, "# NOTE: truncated — the Go-file cap was reached; the graph is partial.\n")
	}
	io.WriteString(w, "@base <https://andromedacli.com/ontology/> .\n")
	io.WriteString(w, "@prefix am: <https://andromedacli.com/ns#> .\n")
	io.WriteString(w, "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n")
	io.WriteString(w, "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n\n")
	io.WriteString(w, codeVocabulary)

	// Map each parsed package's import path to its IRI, so internal imports can link precisely.
	pkgIRIByImport := map[string]string{}
	for _, p := range cm.Packages {
		pkgIRIByImport[p.ImportPath] = pkgIRI(p.Dir)
	}

	for _, p := range cm.Packages {
		writePackageBlock(w, p, pkgIRIByImport)
	}

	if len(cm.Calls) > 0 {
		io.WriteString(w, "# --- calls ---\n")
		for _, e := range cm.Calls {
			pred := "am:calls"
			if e.Approx {
				pred = "am:callsApprox"
			}
			io.WriteString(w, codeFuncIRI(e.FromDir, e.FromFunc)+" "+pred+" "+codeFuncIRI(e.ToDir, e.ToFunc)+" .\n")
		}
		io.WriteString(w, "\n")
	}

	if len(cm.Implements) > 0 {
		io.WriteString(w, "# --- implements (structural) ---\n")
		for _, e := range cm.Implements {
			io.WriteString(w, codeTypeIRI(e.TypeDir, e.TypeName)+" am:implements "+codeTypeIRI(e.IfaceDir, e.IfaceName)+" .\n")
		}
		io.WriteString(w, "\n")
	}
}

// writePackageBlock emits a package node and its type/function nodes. pkgIRIByImport maps a parsed
// package's import path to its IRI, so module-internal imports link to real package nodes.
func writePackageBlock(w io.Writer, p *CodePackage, pkgIRIByImport map[string]string) {
	// Package node.
	io.WriteString(w, pkgIRI(p.Dir)+" a am:Package ;\n")
	io.WriteString(w, "    rdfs:label "+ttlString(p.Name)+" ;\n")
	io.WriteString(w, "    am:packageName "+ttlString(p.Name)+" ;\n")
	io.WriteString(w, "    am:importPath "+ttlString(p.ImportPath)+" ;\n")
	io.WriteString(w, "    am:fileCount "+strconv.Itoa(len(p.Files))+" ;\n")
	io.WriteString(w, "    am:typeCount "+strconv.Itoa(len(p.Types))+" ;\n")
	io.WriteString(w, "    am:funcCount "+strconv.Itoa(len(p.Funcs))+" ;\n")

	var internalRefs []string
	external := 0
	for _, ip := range p.Imports {
		if iri, ok := pkgIRIByImport[ip]; ok {
			internalRefs = append(internalRefs, iri)
		} else {
			external++
		}
	}
	io.WriteString(w, "    am:externalImportCount "+strconv.Itoa(external))
	if len(internalRefs) > 0 {
		io.WriteString(w, " ;\n    am:imports "+joinList(internalRefs))
	}
	if decls := declarationIRIs(p); len(decls) > 0 {
		io.WriteString(w, " ;\n    am:declares "+joinList(decls))
	}
	io.WriteString(w, " .\n")

	// Method sets per type (receiver -> method func IRIs) for am:hasMethod.
	methodsOf := map[string][]string{}
	for _, f := range p.Funcs {
		if f.Recv != "" {
			methodsOf[f.Recv] = append(methodsOf[f.Recv], codeFuncIRI(p.Dir, f.localID()))
		}
	}

	for _, t := range p.Types {
		class := "am:Type"
		switch t.Kind {
		case "struct":
			class = "am:Struct"
		case "interface":
			class = "am:Interface"
		}
		io.WriteString(w, codeTypeIRI(p.Dir, t.Name)+" a "+class+" ;\n")
		io.WriteString(w, "    rdfs:label "+ttlString(t.Name)+" ;\n")
		io.WriteString(w, "    am:inPackage "+pkgIRI(p.Dir)+" ;\n")
		io.WriteString(w, "    am:exported "+strconv.FormatBool(t.Exported)+" ;\n")
		if methods := methodsOf[t.Name]; len(methods) > 0 {
			sort.Strings(methods)
			io.WriteString(w, "    am:hasMethod "+joinList(methods)+" ;\n")
		}
		io.WriteString(w, "    am:definedIn "+fileIRI(t.File)+" .\n")
	}

	for _, f := range p.Funcs {
		class := "am:Function"
		if f.Recv != "" {
			class = "am:Method"
		}
		io.WriteString(w, codeFuncIRI(p.Dir, f.localID())+" a "+class+" ;\n")
		io.WriteString(w, "    rdfs:label "+ttlString(f.Name)+" ;\n")
		io.WriteString(w, "    am:inPackage "+pkgIRI(p.Dir)+" ;\n")
		io.WriteString(w, "    am:exported "+strconv.FormatBool(f.Exported)+" ;\n")
		if f.Recv != "" {
			io.WriteString(w, "    am:receiver "+ttlString(f.Recv)+" ;\n")
		}
		io.WriteString(w, "    am:paramCount "+strconv.Itoa(f.Params)+" ;\n")
		io.WriteString(w, "    am:resultCount "+strconv.Itoa(f.Results)+" ;\n")
		io.WriteString(w, "    am:definedIn "+fileIRI(f.File)+" .\n")
	}
	io.WriteString(w, "\n")
}

// declarationIRIs lists a package's type and function IRIs (types first, both already sorted).
func declarationIRIs(p *CodePackage) []string {
	out := make([]string, 0, len(p.Types)+len(p.Funcs))
	for _, t := range p.Types {
		out = append(out, codeTypeIRI(p.Dir, t.Name))
	}
	for _, f := range p.Funcs {
		out = append(out, codeFuncIRI(p.Dir, f.localID()))
	}
	return out
}

// codeStats summarizes the code model for the manifest and CLI output.
type codeStats struct {
	Packages    int  `json:"packages"`
	Types       int  `json:"types"`
	Funcs       int  `json:"funcs"`
	Calls       int  `json:"calls"`
	Implements  int  `json:"implements"`
	FilesParsed int  `json:"filesParsed"`
	Truncated   bool `json:"truncated"`
}

func (cm *CodeModel) stats() codeStats {
	types, funcs := 0, 0
	for _, p := range cm.Packages {
		types += len(p.Types)
		funcs += len(p.Funcs)
	}
	return codeStats{
		Packages:    len(cm.Packages),
		Types:       types,
		Funcs:       funcs,
		Calls:       len(cm.Calls),
		Implements:  len(cm.Implements),
		FilesParsed: cm.Files,
		Truncated:   cm.Truncated,
	}
}

// Stats renders a short human summary of the code graph for CLI/TUI output.
func (cm *CodeModel) Stats() string {
	s := cm.stats()
	line := "code graph: " +
		strconv.Itoa(s.Packages) + " packages, " +
		strconv.Itoa(s.Types) + " types, " +
		strconv.Itoa(s.Funcs) + " funcs, " +
		strconv.Itoa(s.Calls) + " calls, " +
		strconv.Itoa(s.Implements) + " implements"
	if s.Truncated {
		line += " (truncated)"
	}
	return line
}

// --- code-graph IRIs -----------------------------------------------------

// pkgKey is a stable, non-empty key for a package directory ("(root)" for the module root).
func pkgKey(dir string) string {
	if dir == "" {
		return "(root)"
	}
	return dir
}

func pkgIRI(dir string) string { return "<pkg/" + iriEscape(pkgKey(dir)) + ">" }
func codeTypeIRI(dir, name string) string {
	return "<type/" + iriEscape(pkgKey(dir)) + "/" + iriEscape(name) + ">"
}
func codeFuncIRI(dir, localID string) string {
	return "<func/" + iriEscape(pkgKey(dir)) + "/" + iriEscape(localID) + ">"
}

// joinList renders a comma-separated Turtle object list.
func joinList(items []string) string {
	out := ""
	for i, s := range items {
		if i > 0 {
			out += " , "
		}
		out += s
	}
	return out
}
