package ontology

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// TTL serializes the model as a Turtle document describing the project, its directories, and its
// files, plus the containment (am:contains / am:inDirectory) relationships between them. The output
// is deterministic — no timestamps — so an unchanged tree yields identical bytes.
func (m *Model) TTL() string {
	var b strings.Builder
	b.WriteString("# Andromeda ontology — a deterministic structural map of this workspace.\n")
	b.WriteString("# Generated by `andromeda ontology`; regenerate to update, do not hand-edit.\n")
	b.WriteString("@base <https://andromedacli.com/ontology/> .\n")
	b.WriteString("@prefix am: <https://andromedacli.com/ns#> .\n")
	b.WriteString("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n\n")

	// Build the containment tree: parent path ("." = project root) -> child IRIs, subdirs first
	// (both m.Dirs and m.Files are sorted, so each child list is deterministic).
	children := map[string][]string{}
	for _, d := range m.Dirs {
		p := path0(d)
		children[p] = append(children[p], dirIRI(d))
	}
	for _, f := range m.Files {
		children[f.Dir] = append(children[f.Dir], fileIRI(f.Path))
	}

	// Project
	b.WriteString("<project> a am:Project ;\n")
	b.WriteString("    rdfs:label " + ttlString(m.Name) + " ;\n")
	b.WriteString("    am:fileCount " + strconv.Itoa(len(m.Files)) + " ;\n")
	b.WriteString("    am:directoryCount " + strconv.Itoa(len(m.Dirs)))
	for _, lang := range sortedKeys(m.Languages) {
		b.WriteString(" ;\n    am:usesLanguage " + ttlString(lang))
	}
	writeContains(&b, children["."])
	b.WriteString(" .\n\n")

	// Directories
	for _, d := range m.Dirs {
		b.WriteString(dirIRI(d) + " a am:Directory ;\n")
		b.WriteString("    rdfs:label " + ttlString(baseName(d)) + " ;\n")
		b.WriteString("    am:path " + ttlString(d) + " ;\n")
		b.WriteString("    am:inDirectory " + parentIRI(d))
		writeContains(&b, children[d])
		b.WriteString(" .\n")
	}
	b.WriteString("\n")

	// Files
	for _, f := range m.Files {
		b.WriteString(fileIRI(f.Path) + " a am:File ;\n")
		b.WriteString("    rdfs:label " + ttlString(f.Name) + " ;\n")
		b.WriteString("    am:path " + ttlString(f.Path) + " ;\n")
		if f.Ext != "" {
			b.WriteString("    am:extension " + ttlString(f.Ext) + " ;\n")
		}
		if f.Language != "" {
			b.WriteString("    am:language " + ttlString(f.Language) + " ;\n")
		}
		b.WriteString("    am:kind " + ttlString(f.Kind) + " ;\n")
		b.WriteString("    am:byteSize " + strconv.FormatInt(f.Size, 10) + " ;\n")
		if f.Summary != "" {
			b.WriteString("    am:summary " + ttlString(f.Summary) + " ;\n")
		}
		b.WriteString("    am:inDirectory " + parentIRI(f.Path) + " .\n")
	}
	return b.String()
}

// Write regenerates the structural ontology artifacts under <root>/.andromeda/ontology/ (project.ttl
// and a manifest.json), replacing them atomically. It returns the path to the written .ttl file. This
// is the structure-only path; Generate additionally builds the AST-level code graph.
func Write(root string, m *Model) (string, error) {
	dir := filepath.Join(root, markerDir, ontologySubdir)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	ttlPath := filepath.Join(dir, "project.ttl")
	if err := atomicWrite(ttlPath, []byte(m.TTL())); err != nil {
		return "", err
	}
	if err := atomicWrite(filepath.Join(dir, "manifest.json"), m.manifest(nil, "")); err != nil {
		return "", err
	}
	return ttlPath, nil
}

// Generate scans the workspace and writes both ontologies under <root>/.andromeda/ontology/: the
// structural project.ttl (files/directories/containment) and the AST-level code.ttl (packages, types,
// functions, and their import/call/implements correlations), plus a combined manifest. It returns the
// structural and code models. The code graph is streamed per package so output stays manageable.
func Generate(ctx context.Context, root string) (*Model, *CodeModel, error) {
	m, err := Scan(ctx, root)
	if err != nil {
		return nil, nil, err
	}
	cm, err := ScanCode(ctx, root, m)
	if err != nil {
		return nil, nil, err
	}
	dir := filepath.Join(root, markerDir, ontologySubdir)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, nil, err
	}
	if err := atomicWrite(filepath.Join(dir, "project.ttl"), []byte(m.TTL())); err != nil {
		return nil, nil, err
	}
	_, codeHash, err := WriteCode(root, cm)
	if err != nil {
		return nil, nil, err
	}
	if err := atomicWrite(filepath.Join(dir, "manifest.json"), m.manifest(cm, codeHash)); err != nil {
		return nil, nil, err
	}
	return m, cm, nil
}

// Remove deletes the generated ontology directory. Missing is not an error.
func Remove(root string) error {
	err := os.RemoveAll(filepath.Join(root, markerDir, ontologySubdir))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

// Dir returns the ontology output directory for a workspace root.
func Dir(root string) string { return filepath.Join(root, markerDir, ontologySubdir) }

// Stats renders a short human summary of the model for CLI/TUI output.
func (m *Model) Stats() string {
	langs := sortedKeys(m.Languages)
	parts := make([]string, 0, len(langs))
	for _, l := range langs {
		parts = append(parts, fmt.Sprintf("%s ×%d", l, m.Languages[l]))
	}
	langLine := "—"
	if len(parts) > 0 {
		langLine = strings.Join(parts, ", ")
	}
	return fmt.Sprintf("%d files across %d directories\nlanguages: %s", len(m.Files), len(m.Dirs), langLine)
}

// manifest is a deterministic JSON sidecar: counts, language profile, and a content hash over the
// (path, size) pairs so a caller can detect whether a re-scan would change anything. When a code
// model is supplied (Generate path), it also records the code-graph stats and a content hash of
// code.ttl; when nil (structure-only Write path), the output is the original structural manifest.
func (m *Model) manifest(cm *CodeModel, codeHash string) []byte {
	h := sha256.New()
	for _, f := range m.Files {
		_, _ = fmt.Fprintf(h, "%s\x00%d\n", f.Path, f.Size)
	}
	base := struct {
		Name           string         `json:"name"`
		FileCount      int            `json:"fileCount"`
		DirectoryCount int            `json:"directoryCount"`
		Languages      map[string]int `json:"languages"`
		Hash           string         `json:"hash"`
	}{m.Name, len(m.Files), len(m.Dirs), m.Languages, hex.EncodeToString(h.Sum(nil))}

	var data []byte
	if cm == nil {
		data, _ = json.MarshalIndent(base, "", "  ")
	} else {
		ext := struct {
			Name           string         `json:"name"`
			FileCount      int            `json:"fileCount"`
			DirectoryCount int            `json:"directoryCount"`
			Languages      map[string]int `json:"languages"`
			Hash           string         `json:"hash"`
			Code           codeStats      `json:"code"`
			CodeHash       string         `json:"codeHash"`
		}{base.Name, base.FileCount, base.DirectoryCount, base.Languages, base.Hash, cm.stats(), codeHash}
		data, _ = json.MarshalIndent(ext, "", "  ")
	}
	return append(data, '\n')
}

// atomicWrite writes data to path via a temp file + rename, with owner-only perms.
func atomicWrite(path string, data []byte) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// --- Turtle helpers -------------------------------------------------------

func fileIRI(p string) string { return "<f/" + iriEscape(p) + ">" }
func dirIRI(p string) string  { return "<d/" + iriEscape(p) + ">" }

// parentIRI is the containing directory's IRI, or <project> when the parent is the root.
func parentIRI(p string) string {
	parent := path0(p)
	if parent == "." || parent == "" {
		return "<project>"
	}
	return dirIRI(parent)
}

func baseName(p string) string { return p[strings.LastIndexByte(p, '/')+1:] }

// writeContains appends an am:contains predicate listing the child IRIs, if any.
func writeContains(b *strings.Builder, kids []string) {
	if len(kids) == 0 {
		return
	}
	b.WriteString(" ;\n    am:contains " + strings.Join(kids, " , "))
}

// sortedKeys returns the map keys in lexical order (deterministic iteration).
func sortedKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ttlString renders s as a Turtle double-quoted string literal, escaping per the grammar.
func ttlString(s string) string {
	r := strings.NewReplacer(
		"\\", "\\\\",
		"\"", "\\\"",
		"\n", "\\n",
		"\r", "\\r",
		"\t", "\\t",
	)
	return "\"" + r.Replace(s) + "\""
}

// iriEscape percent-encodes the characters not permitted in a Turtle relative IRI reference.
func iriEscape(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r <= 0x20, r == '<', r == '>', r == '"', r == '{', r == '}',
			r == '|', r == '^', r == '`', r == '\\', r == '%':
			fmt.Fprintf(&b, "%%%02X", r)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
