package graph

import (
	"fmt"
	"sort"
	"strings"

	"github.com/datamaia/andromeda/internal/ontology"
)

// renderMarkdown produces the human-readable note set for a workspace: a top-level index plus one
// note per top-level group. Keys are slash-separated paths relative to the graph output directory;
// values are the file contents. Output is deterministic (inputs are already sorted).
func renderMarkdown(m *ontology.Model) map[string]string {
	out := map[string]string{"index.md": renderIndex(m)}
	for _, grp := range topLevelGroups(m) {
		out["groups/"+groupSlug(grp)+".md"] = renderGroup(m, grp)
	}
	return out
}

// renderIndex is the overview note: counts, language profile, a Mermaid map of the top-level
// structure, and links to the per-group notes.
func renderIndex(m *ontology.Model) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — workspace map\n\n", m.Name)
	b.WriteString("Deterministic structural graph generated by `andromeda graph`. ")
	b.WriteString("Regenerate to update; do not hand-edit.\n\n")
	fmt.Fprintf(&b, "- **Files:** %d\n- **Directories:** %d\n\n", len(m.Files), len(m.Dirs))

	b.WriteString("## Languages\n\n")
	if len(m.Languages) == 0 {
		b.WriteString("_none detected_\n\n")
	} else {
		b.WriteString("| Language | Files |\n| --- | ---: |\n")
		for _, lang := range sortedKeys(m.Languages) {
			fmt.Fprintf(&b, "| %s | %d |\n", lang, m.Languages[lang])
		}
		b.WriteString("\n")
	}

	b.WriteString("## Top-level structure\n\n")
	b.WriteString("```mermaid\n")
	b.WriteString(mermaidTopLevel(m))
	b.WriteString("```\n\n")

	b.WriteString("## Groups\n\n")
	groups := topLevelGroups(m)
	if len(groups) == 0 {
		b.WriteString("_empty workspace_\n")
		return b.String()
	}
	for _, grp := range groups {
		n := len(filesInGroup(m, grp))
		fmt.Fprintf(&b, "- [%s](groups/%s.md) — %d file%s\n", grp, groupSlug(grp), n, plural(n))
	}
	return b.String()
}

// renderGroup is one note per top-level group: every file in that subtree with its kind and cheap
// summary, ordered by path.
func renderGroup(m *ontology.Model, group string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", group)
	fmt.Fprintf(&b, "Files under `%s` in %s.\n\n", group, m.Name)
	b.WriteString("| File | Kind | Language | Summary |\n| --- | --- | --- | --- |\n")
	for _, f := range filesInGroup(m, group) {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
			f.Path, dashIfEmpty(f.Kind), dashIfEmpty(f.Language), dashIfEmpty(mdCell(f.Summary)))
	}
	return b.String()
}

// mermaidTopLevel renders a flowchart linking the project to each top-level group (directories and
// root-level files), kept shallow so the diagram stays legible on large repos.
func mermaidTopLevel(m *ontology.Model) string {
	var b strings.Builder
	b.WriteString("flowchart TD\n")
	root := mermaidID("project")
	fmt.Fprintf(&b, "  %s([%s])\n", root, mermaidLabel(m.Name))
	for _, grp := range topLevelGroups(m) {
		id := mermaidID(grp)
		shapeOpen, shapeClose := "[", "]"
		if isTopLevelDir(m, grp) {
			shapeOpen, shapeClose = "[/", "/]" // parallelogram for directories
		}
		fmt.Fprintf(&b, "  %s --> %s%s%s%s\n", root, id, shapeOpen, mermaidLabel(grp), shapeClose)
	}
	return b.String()
}

// --- group helpers -------------------------------------------------------

// topLevelGroups is the sorted, unique set of first path segments across all files and directories.
func topLevelGroups(m *ontology.Model) []string {
	set := map[string]struct{}{}
	for _, d := range m.Dirs {
		set[topLevel(d)] = struct{}{}
	}
	for _, f := range m.Files {
		set[topLevel(f.Path)] = struct{}{}
	}
	groups := make([]string, 0, len(set))
	for g := range set {
		groups = append(groups, g)
	}
	sort.Strings(groups)
	return groups
}

// filesInGroup returns the files whose top-level segment is group, preserving Files' path order.
func filesInGroup(m *ontology.Model, group string) []ontology.FileNode {
	var fs []ontology.FileNode
	for _, f := range m.Files {
		if topLevel(f.Path) == group {
			fs = append(fs, f)
		}
	}
	return fs
}

// isTopLevelDir reports whether group names a directory (vs. a root-level file).
func isTopLevelDir(m *ontology.Model, group string) bool {
	for _, d := range m.Dirs {
		if d == group {
			return true
		}
	}
	return false
}

// --- formatting helpers --------------------------------------------------

func sortedKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

func dashIfEmpty(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

// mdCell makes a string safe to place inside a Markdown table cell (no pipes or newlines).
func mdCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

// groupSlug makes a filesystem- and link-safe base name for a group note.
func groupSlug(group string) string {
	if group == "" {
		return "_root"
	}
	r := strings.NewReplacer("/", "-", " ", "-", ".", "_")
	return r.Replace(group)
}

// mermaidID derives a syntactically valid Mermaid node id from a group name.
func mermaidID(s string) string {
	if s == "" {
		return "n_root"
	}
	var b strings.Builder
	b.WriteString("n_")
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// mermaidLabel quotes a label so punctuation in a name can't break the diagram.
func mermaidLabel(s string) string {
	return "\"" + strings.ReplaceAll(s, "\"", "'") + "\""
}
